### ISSUE TITLE
Bluetooth Passthrough

### ISSUE THREAD

**Issue by mutlucan96** [Nightmayr-snaps/dolphin-emu-snap#23]
It looks like the guide about Bluetooth passthrough (https://wiki.dolphin-emu.org/index.php?title=Bluetooth_Passthrough#Linux) doesn't apply snap. I couldn't find udev folder. Is it possible to use Bluetooth passthrough with the snap packege?

**Comment by Nightmayr** [comment]
I believe in order to get this to work you should just need to connect the `raw-usb` interface. In the terminal run `snap connect dolphin-emulator:raw-usb` I don't think there is a need to add the udev rule file after connecting this interface. If you want to connect this through a graphical method, if you have the snap store installed, go to Dolphin emulators store page and click permission > Access USB hardware directly

**Comment by mutlucan96** [comment]
I did have given the permission before and it didn't work. Today I installed, set the permission again and it worked somehow. Thanks!

**Comment by mardy** [comment]
Hi, I'm having this issue, on Ubuntu 22.04, that as soon as I turn on BT passthrough and start a game, I get a dialog saying

> Could not find any usable Bluetooth USB adapter for Bluetooth Passthrough.
> The emulated console will now stop.

I have all snap plugs connected (except for the `hidraw` one, for which there is no slot available). My wiimote is paired with the PC and works properly. I do see the options to use it as a controller in emulated mode ("Real Wii Remote"), but the games don't see my controller (whereas it works find in the Dolphin GUI itself). It always connects to the PC as the 4th controller (the 4th led lits up), so I think that if I could use the passthrough option, then Dolphin would be smarter and connect it as the first one.

Any suggestions?
